import { DetailInterface, ListingDataInterface, ListingFilterModel, ListingResponseModel, StandardResponseModel } from './base-listing.model';
import { environment } from 'src/environments/environment';
import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { DashboardModel } from 'src/app/core/models/dashboard/dashboard.model';

@Injectable({
    providedIn: 'root'
})
export abstract class BaseApiService {

    /**
     * The full end point generated by parent class.
     */
    fullPathEndPoint = '/';
    /**
     * Always start the URL with a "/".
     */
    protected apiVersion = '/admin/api/v1';
    protected endPoint = '/';
    protected host: string = environment.apiServer;

    constructor(
        protected http: HttpClient,
    ) {
        // Due to JS class limitation, we need to run this at child class.
        // this.manualConstructor();
    }

    getDashboard(): Observable<DashboardModel> {
        return this.http.get<DashboardModel>(this.fullPathEndPoint);
    }

    getDetail(id: string | number): Observable<DetailInterface> {
        return this.http.get<DetailInterface>(this.fullPathEndPoint + `/${id}`);
    }

    getListing(filter: ListingFilterModel): Observable<ListingResponseModel<ListingDataInterface>> {
        const params: any = this.generateListingParams(filter);

        return this.http.get<ListingResponseModel<ListingDataInterface>>(this.fullPathEndPoint, {
            params,
        });
    }

    protected generateListingParams(filter: ListingFilterModel): any {
        const params: any = {
            currentPage: filter.currentPage,
            IsOrderByDesc: filter.isOrderByDesc,
            take: filter.take,
        };

        if (filter.orderBy) {
            params.OrderBy = filter.orderBy.charAt(0).toUpperCase() + filter.orderBy.slice(1);
        }

        if (filter.keywords.length > 0) {
            params.FilterBy = filter.keywordsField;
            params.FilterString = filter.keywords;
        }

        params.skip = filter.currentPage * filter.take;

        return params;
    }

    protected manualConstructor(): void {
        this.fullPathEndPoint = this.host + this.apiVersion + this.endPoint;
    }

}
